# Generated by Django 4.2 on 2024-04-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('gstcode', models.CharField(max_length=50, null=True)),
                ('gstin', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=250, null=True, unique=True)),
                ('frompin', models.CharField(max_length=50, null=True)),
                ('topin', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
