# Generated by Django 4.2 on 2024-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_statemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemaster',
            name='country',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='statemaster',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
