# Generated by Django 4.2 on 2024-04-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlinetableform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='price',
            field=models.IntegerField(),
        ),
    ]
