# Generated by Django 4.2 on 2024-05-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inlinetableform', '0002_alter_bookdetail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnno', models.CharField(max_length=100)),
                ('cndate', models.DateField()),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inno', models.CharField(max_length=100)),
                ('indate', models.DateField()),
                ('invalue', models.IntegerField()),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inlinetableform.consignment')),
            ],
        ),
    ]
