# Generated by Django 4.2 on 2024-05-01 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inlinetableform', '0003_consignment_invoicedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('invoice_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inlinetableform.invoicedetail')),
            ],
        ),
    ]
